directory index file exists ... ERROR
document root escaping forbidden ... FAIL
Send bad http headers ... ok
file located in nested folders ... ok
absent file returns 404 ... ok
urlencoded filename ... ok
query string after filename ... FAIL
filename with spaces ... ok
Content-Type for .css ... ok
Content-Type for .gif ... ok
Content-Type for .html ... ok
Content-Type for .jpeg ... ok
Content-Type for .jpg ... ok
Content-Type for .js ... ok
Content-Type for .png ... ok
Content-Type for .swf ... ok
head method support ... ok
directory index file absent ... FAIL
large file downloaded correctly ... ok
post method forbidden ... ok
Server header exists ... ok

======================================================================
ERROR: directory index file exists
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./httptest.py", line 37, in test_directory_index
    data = r.read()
  File "/usr/lib/python2.7/httplib.py", line 586, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 695, in _safe_read
    raise IncompleteRead(''.join(s), amt)
IncompleteRead: IncompleteRead(34 bytes read, 4062 more expected)

======================================================================
FAIL: document root escaping forbidden
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./httptest.py", line 125, in test_document_root_escaping
    self.assertIn(int(r.status), (400, 403, 404))
AssertionError: 200 not found in (400, 403, 404)

======================================================================
FAIL: query string after filename
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./httptest.py", line 82, in test_file_with_query_string
    self.assertEqual(int(r.status), 200)
AssertionError: 404 != 200

======================================================================
FAIL: directory index file absent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./httptest.py", line 49, in test_index_not_found
    self.assertEqual(int(r.status), 403)
AssertionError: 404 != 403

----------------------------------------------------------------------
Ran 21 tests in 0.062s

FAILED (failures=3, errors=1)
